### ISSUE TITLE
Presentation server

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#11]
Launch one or more servers that host a number of presenter (#5) containers behind a load balancer.

We may also host an instance of the mapping service (#4) here.

**Comment by jrperritt** [comment]
Is this going to happen as part of the `deploy` repo or in a separate repo/playbook?

**Comment by smashwilson** [comment]
I'll do it as part of the deploy repo, yeah.

**Comment by smashwilson** [comment]
Provisioned at http://deconst.devsupport.me/.
