### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#114]
I'm seeing the following stack trace in the presenter logs:

```
message: 'No content for ID [https://github.com/rackerlabs/docs-developer-blog/images/2013-04-25-getting-started-with
_http_outgoing.js:335
 throw new Error('Can\'t set headers after they are sent.');
 ^
Error: Can't set headers after they are sent.
 at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
 at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:700:10)
 at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:154:12)
 at /usr/src/app/src/routers/content.js:106:17
 at /usr/src/app/src/services/content/filter.js:12:13
 at next (/usr/src/app/node_modules/mware/index.js:56:28)
at /usr/src/app/src/routers/content.js:98:20
 at exec (/usr/src/app/node_modules/mware/index.js:50:23)
 at next (/usr/src/app/node_modules/mware/index.js:60:9)
 at /usr/src/app/src/routers/content.js:84:20
```

**Comment by ktbartholomew** [comment]
I can't replicate this exact error, so there must be something unique about the request that's not being shown in the logs. Running it locally, the "No content for ID ..." message results in a healthy, albeit un-styled 404 page. Creating a separate issue for that.

**Comment by annegentle** [comment]
I get these errors locally that _seem_ related to "Can't set headers after they are sent" when I use the jekyll preparer to load blog content. Here's an example in case it's helpful:

content_1   | 2015-07-02T20:20:36.675Z - verbose: PUT /content/https%3A%2F%2Fgithub.com%2Frackerlabs%2Fdocs-developer-blog%2Fblog%2Fpage30
content_1   | 2015-07-02T20:20:36.676Z - debug: Request authenticated as [jekyll]
content_1   | 2015-07-02T20:20:36.677Z - info: (jekyll) Storing content with ID: [https://github.com/rackerlabs/docs-developer-blog/blog/page30]
mongo_1     | 2015-07-02T20:21:06.590+0000 [clientcursormon] mem (MB) res:44 virt:505
mongo_1     | 2015-07-02T20:21:06.590+0000 [clientcursormon]  mapped (incl journal view):320
mongo_1     | 2015-07-02T20:21:06.590+0000 [clientcursormon]  connections:5
presenter_1 | 2015-07-02T20:21:08.012Z - verbose: GET /
presenter_1 | 2015-07-02T20:21:08.015Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.030Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.031Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.033Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.033Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.033Z - error: No content found for content at ID [null]
presenter_1 | 2015-07-02T20:21:08.034Z - error:  
presenter_1 | { statusCode: '404' }
presenter_1 | 2015-07-02T20:21:08.037Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.037Z - error: No content found for content at ID [null]
presenter_1 | 2015-07-02T20:21:08.387Z - verbose: GET /favicon.ico
presenter_1 | 2015-07-02T20:21:08.388Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.398Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.398Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.400Z - error: Unable to read /var/control-repo/config/content.json
presenter_1 | 2015-07-02T20:21:08.400Z - error: No content found for content at ID [null]
presenter_1 | 2015-07-02T20:21:08.400Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.400Z - error:  
presenter_1 | { statusCode: '404' }
presenter_1 | 2015-07-02T20:21:08.401Z - warn: Trying to send error response but headers already sent.
presenter_1 | 2015-07-02T20:21:08.401Z - error: No content found for content at ID [null]

**Comment by ktbartholomew** [comment]
I'm _pretty_ sure https://github.com/deconst/presenter/pull/53 should get rid of all these errors in the presenter.
