### ISSUE TITLE
Page JSON schema

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#12]
This is a venue for discussions about what needs to be in the JSON documents that each renderer (#2, #3) produces. Rather than bikeshedding about this a bunch up front, I'd prefer to see what the presenter (#5) actually needs and add it to the renderers as it's used.

To kick us off, here's what the `.rst` renderer is producing right now, which is a tiny change from the default Sphinx JSON renderer:

``` json
{
  "body": "-- rendered html --",
  "display_toc": true,
  "title": "Deconst",
  "sourcename": "index.txt",
  "customsidebar": null,
  "current_page_name": "index",
  "next": {
    "link": "writing-docs/",
    "title": "Writing Documentation for Deconst"
  },
  "rellinks": [
    [
      "genindex",
      "General Index",
      "I",
      "index"
    ],
    [
      "writing-docs/index",
      "Writing Documentation for Deconst",
      "N",
      "next"
    ]
  ],
  "meta": {},
  "parents": [],
  "sidebars": null,
  "toc": "-- rendered html --",
  "prev": null,
  "hello": "Sup",
  "metatags": ""
}
```

**Comment by rgbkrk** [comment]
The bits that Jekyll gives us for a post are:
- Title (`post.title`)
- Raw content (`post.content`)
- Rendered content, using a converter:

``` ruby
converter = site.getConverterImpl(Jekyll::Converters::Markdown)
converter.convert(post.content)
```

All the front matter ends up in a hash called `post.data`, which typically includes `layout`, `title` (again), `date`, `categories`. I don't think those are strong requirements, but those are points of influence in the tooling.

**Comment by rgbkrk** [comment]
Ok, a bit more, using some Ruby hackery since `post.inspect` didn't give me a full dump and I wasn't seeing useful bits in the jekyll docs.

```
@site:#<Jekyll::Site:0x007fc2dac04410>
@dir:
@base:/Users/rgbkrk/code/jekyllson/legit/_posts
@name:2015-03-12-welcome-to-jekyll.markdown
@categories:jekyll:update
@date:2015-03-12 08:46:52 -0500
@slug:welcome-to-jekyll
@ext:.markdown
@content:You’ll find this post in your `_posts` directory. <manually trimmed>
@data:{"layout"=>"post", "title"=>"Welcome to Jekyll!", "date"=>2015-03-12 08:46:52 -0500, "categories"=>"jekyll update", "whatever"=>"stuff"}
@extracted_excerpt:You’ll find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.
@tags:
@converters:#<Jekyll::Converters::Markdown:0x007fc2dabc4950>:#<Jekyll::Converters::Identity:0x007fc2dabc4310>
@url:/jekyll/update/2015/03/12/welcome-to-jekyll.html
```

**Comment by rgbkrk** [comment]
The big difference between RST and Jekyll Markdown is that RST thinks of content relative to other content based on the build context.

**Comment by kenperkins** [comment]
Let me know if this has any impact on deconst/content-service#1

**Comment by rgbkrk** [comment]
It's definitely going to have impact, since validation should happen at the content service.

**Comment by smashwilson** [comment]
Based on the presenter, here's the only requirement for the initial metadata envelope:

``` json
{
  "body": "...",
}
```

Because this is one of the last issues in the [0.1 milestone](https://github.com/deconst/deconst-docs/milestones/%5B0.1%5D%20Build%20Something), I'm going to add a "metadata envelope schema" document to the docs and close it off.
