### ISSUE TITLE
Atom feed looks malformed

### ISSUE THREAD

**Issue by ktbartholomew** [deconst/deconst-docs#120]
Duplicated from @major's issue: https://github.com/rackerlabs/developer.rackspace.com/issues/1165

---

If I try to access https://developer.rackspace.com/atom.xml I get a redirect over to https://developer.rackspace.com/atom.xml/ but the RSS/Atom feed looks to be malformed.  There's a bunch of HTML wrapped around it.  My RSS feed reader can't read the feed.

**Comment by smashwilson** [comment]
Oh yeah, the presenter used to handle any metadata envelope that didn't specify a layout with a "null layout" that passed the body through as-is. It also respected a `content_type` attribute to serve it with the proper content type.

**Comment by smashwilson** [comment]
The things I didn't think to write tests for :wink:

**Comment by ktbartholomew** [comment]
@major @smashwilson The atom feed has been restored: https://developer.rackspace.com/atom.xml

**Comment by major** [comment]
And there was much rejoicing.

![Dance](http://media.giphy.com/media/v6u0T7dXN6lPi/giphy.gif)
