### ISSUE TITLE
Redirect handler does not handle query paths correctly

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#122]
From email:

> Hello,
> 
> My Support Team has had a customer come into chat asking about the status of this page:
> 
> https://developer.rackspace.com/docs/cloud-servers/getting-started/?lang=python
> 
> It appears to be in a redirect loop or just unavailable. Is this the right group to be emailing regarding this?
> 
> Kindly,
> 
> Paul Widsten
> International SMB

This sounds like the same issue that @DonSchenck was having with the SDKs links. My suspicion is that the trailing-URL redirection handler is being too aggressive and infinitely redirecting requests with query parameters.

**Comment by ktbartholomew** [comment]
This is fixed with https://github.com/deconst/presenter/pull/52, pending deployment
