### ISSUE TITLE
Share credentials.yml more conveniently

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#129]
The `credentials.yml` files for each deployment are changing more frequently than I thought they would, and it's making it difficult for all of us to stay on the same page. I'd like to establish a new mechanism for us to stay up to date with deployment-specific and sensitive information.

Proposal: use [GPG](https://gpgtools.org/) in symmetric encryption mode and store the encrypted file in the appropriate control repository for each deployment.

``` bash
# Encrypt it
gpg -o ~/writing/nexus-control/credentials-production.yml.gpg -c credentials.yml

# Decrypt it
gpg -o credentials.yml ~/writing/nexus-control/credentials-production.yml.gpg
```

@ktbartholomew Sound okay to you?

**Comment by ktbartholomew** [comment]
My only beef with GPG is that it's not installed by default, so we're looking at at least one additional step for most people. On Macs, this is just a `brew install` away, but that also assumes the developer has Brew installed.

I'm wondering if using OpenSSL directly is worth the little bit of added syntax (that can be abstracted with something like `script/encrypt` and `script/decrypt`) in exchange for having fewer dependencies to install.

We'd probably want Rackspace security to weigh in here, too. I have a feeling they wouldn't like a secret sitting on a public server even if it is encrypted.

**Comment by smashwilson** [comment]
> I'm wondering if using OpenSSL directly is worth the little bit of added syntax (that can be abstracted with something like script/encrypt and script/decrypt) in exchange for having fewer dependencies to install.

We could do that. I'd probably ask you to double-check my openssl invocation to make sure I'm not making any obvious mistakes.

> We'd probably want Rackspace security to weigh in here, too. I have a feeling they wouldn't like a secret sitting on a public server even if it is encrypted.

Hrm. If you're okay still needing to VPN in every time you run the playbook, then we really haven't made anything easier to use.

Maybe I could do something like store a checksum of the current `credentials.yml` file somewhere instead, so you can at least verify that you have the latest version before you run it? That would let us ensure that we're staying in sync and keep you from having to grab the latest version _every_ time, and at least save you some hassle when it's unnecessary.

**Comment by ktbartholomew** [comment]
I realized after throwing in the Rackspace security :bomb: that whatever solution we implement here is in deconst proper and so needs to be useful/applicable to the general public. In that sense, I think storing the encrypted credentials directly in the repo would be fine for most use cases and fine for right now.  

There's always the easy solution of making the repo private if we don't want our ciphertext sitting out in the open.

**Comment by smashwilson** [comment]
> I realized after throwing in the Rackspace security :bomb: that whatever solution we implement here is in deconst proper and so needs to be useful/applicable to the general public.

This is true, although "hide it in a private network" or leaving it as "find a solution that works for you" are not unreasonable things to do. We'd only be locking it to Rackspace-specific stuff if I started writing scripts around internal APIs.

> In that sense, I think storing the encrypted credentials directly in the repo would be fine for most use cases and fine for right now.

:+1: Alright, cool.

Really, like any security-related decision, it comes down to the level of risk we're willing to accept. As long as I don't bungle the openssl incantation we use, this should be less risk than we were incurring in the old architecture, which was using `ansible-vault`, which (according to some of our more crypto-savvy team members) was "not fatally weak but also not as strong as it could be."

> There's always the easy solution of making the repo private if we don't want our ciphertext sitting out in the open.

Actually, that's a great compromise. I'll make a private repo that we can use to store the encrypted credential files in. That way:
1. Even the ciphertext is not accessible to the general public;
2. It's still encrypted, so leaks in GitHub's security won't expose all of our stuff; and
3. We still don't have to VPN in just to keep our credentials sync'd.

**Comment by smashwilson** [comment]
:sparkles:
