### ISSUE TITLE
Create an architecture diagram for the docs

### ISSUE THREAD

**Issue by rgbkrk** [deconst/deconst-docs#14]
To start us off, I'll post images that we mocked up earlier. Eventually we can have a more formal graphic.

**Comment by rgbkrk** [comment]
![img_2681](https://cloud.githubusercontent.com/assets/836375/6624369/ceac9cd2-c8b6-11e4-899a-4807796dbccd.JPG)

**Comment by rgbkrk** [comment]
![img_2682](https://cloud.githubusercontent.com/assets/836375/6624392/e289b06e-c8b6-11e4-921a-e8c878b871d2.JPG)

**Comment by rgbkrk** [comment]
![img_2683](https://cloud.githubusercontent.com/assets/836375/6624400/ea5ffa50-c8b6-11e4-84ed-da6ca97178e9.JPG)

**Comment by rgbkrk** [comment]
![img_2681](https://cloud.githubusercontent.com/assets/836375/6624405/f2788ba8-c8b6-11e4-8358-a9c2185e452b.JPG)

**Comment by smashwilson** [comment]
:+1: Sweet, thanks!

**Comment by rgbkrk** [comment]
Next up the draw.io diagrams from @kenperkins

**Comment by rgbkrk** [comment]
![image](https://cloud.githubusercontent.com/assets/836375/6624648/a826d6a2-c8b8-11e4-9fdb-d0026bc98d88.png)

**Comment by kenperkins** [comment]
In the above image, the pipeline layer is where any logic where you'd transform the source into an HTTP request into the content system.

**Comment by smashwilson** [comment]
Implemented as part of #17.
