### ISSUE TITLE
Handling Authentication from the preparers.

### ISSUE THREAD

**Issue by rgbkrk** [deconst/deconst-docs#15]
We need some way for potential renderers to publish their batch of content.

Options:
1. PKI
2. API Keys

**Comment by smashwilson** [comment]
Specifically, this is for authentication to the content storage service from the "renderers".

**Comment by rgbkrk** [comment]
It kind of sounds like since we have a mapping service to pull content out (which may be private...) that it might be on that side too.

**Comment by smashwilson** [comment]
:+1: Yes, good point. In general we need authentication at the content store, then.

**Comment by smashwilson** [comment]
I'm leaning toward using an API key, mainly for simplicity. PKI wouldn't be terrible with [keymaster](https://github.com/cloudpipe/keymaster) but it would probably be overkill.

**Comment by rgbkrk** [comment]
Yeah I'm a bigger fan of API keys for user facing services. People understand them. We just have to know how to issue them.

**Comment by chesshacker** [comment]
To throw a few more options out there, here are some options from "Building Microservices" (a recent book and quick read that I'd recommend to anyone interested in this topic)... these are the options listed for service to service authentication:
1. Allow everything inside the perimeter... if it can talk to our content service, we trust it.
2. HTTP(S) Basic Authentication... which has issues if not done with SSL, and if you do it over SSL, well you have to manage the certs.
3. Use SAML or OpenID Connect for your service accounts... would make sense if we were already using SAML or OpenID in the system somewhere, but seems overkill for what we are doing currently
4. Client Certificates... adds a lot of operational complexity
5. HMAC Over HTTP... hash-based messaging code to sign requests. simple implementation, but it requires a shared secret and it's not really a standard, though it has its uses, notable Amazon S3.
6. API Keys... more popular, standard and straightforward

**Comment by smashwilson** [comment]
I've started to implement this using API keys. An admin API key is provided to the content service by its environment (which means it's chosen as part of the Ansible's `credentials.yml` file). User API keys may be acquired by sending a `POST` to the `/keys` resource of the content service, authenticated with the admin key. Requests are authenticated by specifying a valid API token in a custom `Authorization` header, which plays more nicely with proxies and caches than a custom header, say.

My end goal would be to ultimately do API key issuance as part of the automated content repository setup (#8).

#### Ongoing work:
- [x] _content service:_ Generate and accept API keys in the content service. Document the authorization workflow, which endpoints require an API key, and the new endpoints related to generating and revoking keys.
- [x] _asset preparer:_ Construct Authorization headers based on the value of `CONTENT_STORE_APIKEY`.
- [x] _Sphinx preparer:_ Construct Authorization headers.
- [x] _Jekyll preparer:_ Construct Authorization headers.
- [x] _deploy:_ Include the admin API key in the Ansible playbooks.

**Comment by smashwilson** [comment]
Alright! Content store operations (Get, delete, and asset submission) are now protected by API keys, which all of the preparers will provide. The admin API key is specified in the credentials bit of the Ansible playbooks.

The rest of the work here is just to make this more convenient by including key issuance in the automated webhook setup stuff.
