### ISSUE TITLE
Jekyll Preparer should support collections

### ISSUE THREAD

**Issue by ktbartholomew** [deconst/deconst-docs#157]
"Experimental" as they may be, they're useful as hell and will be first-class citizens in Jekyll 3.0

http://jekyllrb.com/docs/collections/

**Comment by ktbartholomew** [comment]
Fixed w/ https://github.com/deconst/preparer-jekyll/pull/21

**Comment by smashwilson** [comment]
:confetti_ball: Nicely done.
