### ISSUE TITLE
"content service" - Build content service

### ISSUE THREAD

**Issue by kenperkins** [deconst/deconst-docs#16]
This is the working design for the content service api.

Assertions:
1. Repo and app will be named `content-service` https://github.com/deconst/content-service
2. MVP for integration with other layers includes
   - Methods
     - `GET /content/:id`  get content by id
     - `PUT /content`  create or update content (id required)
     - `DELETE /content/:id` delete content by id
     - No `POST` as the caller will be providing an ID when submitting or updating content
   - Authored in Node
   - Based on Restify

**Comment by smashwilson** [comment]
:+1:

One thing to note about the `:id` parameters is that we were going to make them URLs (because we need them to... wait for it... "uniformly locate resources.") I guess they'll have to be URL-encoded, then?

Unless this was another one of those non-decisions. @rgbkrk ?

**Comment by kenperkins** [comment]
@smashwilson I see a couple options:
1. we just proxy the full url upstream, i.e.
   - `GET /content/this/is/my/file/key` becomes `/this/is/my/file/key`
2. we urlencode the key, i.e.
   - `GET /content/%2Fthis%2Fis%2Fmy%2Ffile%2Fkey` becomes `/this/is/my/file/key`
3. we use a non-url-based key (?)

**Comment by smashwilson** [comment]
@kenperkins Remember that we need the domain name, too. At current guess IDs will look something like `https://github.com/rackerlabs/docs-cloud-files/some/path/here`, or `https://github.com/rackerlabs/docs-cloud-files/trees/stable/some/path/here`.

I feel like urlencoding would be best - in my opinion, the content store should just consider IDs opaque strings as much as possible.

**Comment by kenperkins** [comment]
I'm ok with running with encoding until proven otherwise. All content into one container? container per FQDN? Your thoughts?

**Comment by kenperkins** [comment]
ID is source path or dest path?

**Comment by smashwilson** [comment]
ID uniquely identifies the content - so, the "source path", although it's a full URL, not a path. The mapping service exists to use a map repository to determine what content ID ("source path") corresponds to an actual request path ("destination path"). The content store should know nothing about the mapping service - it should speak entirely in terms of content IDs ("source paths").

**Comment by kenperkins** [comment]
Perfect, thanks.

**Comment by kenperkins** [comment]
The most trivial version of this has been implemented in https://github.com/deconst/content-service/commit/93e76fc50cee58ab1cdc808adb769c0850f07702. I expect there will be more work to better define the models, etc.

**Comment by kenperkins** [comment]
I believe we can close this, until we have more actionable issues.

**Comment by smashwilson** [comment]
Sure.
