### ISSUE TITLE
Electron crashes on Mac

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#166]
@meker12 has a slightly older Mac with 8GB of RAM and is seeing sporadic shutdowns and restarts. I'm suspecting that this has to do with how RAM-hungry the `deconst-client` VM is. We can probably get away with a leaner VM, although this may impact the number of repositories that it can handle at once.

**Comment by smashwilson** [comment]
Actually, this is looking like a [different crash](https://gist.github.com/meker12/23664b327dbec0718edb).

Bumping the Electron version might help?

**Comment by meker12** [comment]
You can close this when you have a chance.

**Comment by meker12** [comment]
Since we aren't using deconst-client, closing this.
