### ISSUE TITLE
When using a fresh clone of nexus-control, getting Error: Cannot find module 'coffee-script'

### ISSUE THREAD

**Issue by annegentle** [deconst/deconst-docs#168]
After deleting then re-cloning my nexus-control repo locally, I get this in the deconst client:
The control preparer exited with status 1.

Inspecting the containers I see this:

$ docker logs d80
npm WARN package.json nexus-control@1.0.0 No license field.
npm WARN package.json Dependency 'cheerio' exists in both dependencies and devDependencies, using 'cheerio@^0.19.0' from dependencies
npm WARN unmet dependency /var/control-repo/node_modules/grunt requires lodash@'~0.9.2' but will load
npm WARN unmet dependency /var/control-repo/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency /var/control-repo/node_modules/grunt-contrib-less requires lodash@'^2.4.1' but will load
npm WARN unmet dependency /var/control-repo/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency /var/control-repo/node_modules/grunt-contrib-watch requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /var/control-repo/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/control-repo/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by annegentle** [comment]
I also get the same error when trying to run `grunt build` locally in the nexus-control repo.

**Comment by smashwilson** [comment]
Weird. I can't reproduce this. Did you try `rm -rf node_modules/` in the root of your nexus-control clone?

**Comment by annegentle** [comment]
I'm gonna say let's close this Issue. I did `rm -rf node_modules/` and then deleted the entire `nexus-control` repo and re-cloned it. Since then I'm past the coffee-script module being missing.
