### ISSUE TITLE
Usability: user gets error about choosing a preparer due to order of choices

### ISSUE THREAD

**Issue by annegentle** [deconst/deconst-docs#169]
In the deconst client, the dropdown menu for Preparer and choice between Sphinx and Jekyll comes after the Content Repository Path. So the user gets a warning about the preparer type before making a decision on which preparer to use.

**Comment by smashwilson** [comment]
Ah, I hadn't thought about reordering them. I had thought about:
- Automatically detecting the preparer type
- Including the preparer in `_deconst.json`

I'll need similar functionality for automatically configuring Strider builds, by the way.
