### ISSUE TITLE
Styles not working for /docs, other landing pages when using deconst client

### ISSUE THREAD

**Issue by annegentle** [deconst/deconst-docs#170]
Expected result:
When building docs-quickstart, the <containerIP>:<port>/docs built page should look like developer.rackspace.com/docs. Note that it is understood that when you click or enter /docs from a container IP that isn't docs-quickstart, you get Page Not Found in your browser. This is an expectation that the styling will match container-for-container.

Actual result:
There's no filter mechanism in the left-hand sidebar, no boxes around the groups of links.

<img width="1471" alt="screen shot 2015-09-28 at 1 24 24 pm" src="https://cloud.githubusercontent.com/assets/501981/10144672/6d8a1a94-65e4-11e5-9fac-715348c86201.png">

**Comment by smashwilson** [comment]
Looking into it. It's possible that I broke template routing for mapped repositories when I made it work for unmapped repositories.

**Comment by smashwilson** [comment]
Oh, weird, it's doing something strange with the template route file:

```
$ jq . < ~/.deconst/control-0/routes.json 
{
  "developer.rackspace.com": {
    "routes": {
      "developer.rackspace.com": {
        "routes": {
          "^/": "default.html",
          "^/$": "index.html",
          "^/signup": "index.html",
          "^/databases": "databases-index.html",
          "^/blog": "blog-index.html",
          "^/blog/.+?": "blog-single.html",
          "^/blog/page?": "blog-index.html",
          "^/blog/categories": "blog-index.html",
          "^/blog/authors": "blog-index.html",
          "^/docs": "docs-home.html",
          "^/docs/.+?": "docs-page.html",
          "^/docs/user-guides/infrastructure/": "user-guide.html",
          "^/docs/cloud-images/v2/developer-guide": "docs-singlepage.html",
          "^/docs/cloud-load-balancers/v1/developer-guide": "docs-singlepage.html",
          "^/docs/rack-cli/": "rack-cli.html",
          "^/sdks": "sdks-home.html",
          "^/sdks/.+?": "sdks-page.html",
          "\\.xml$": "feed.xml"
        }
      }
    }
  }
}
```

**Comment by smashwilson** [comment]
![screen shot 2015-09-28 at 3 23 42 pm](https://cloud.githubusercontent.com/assets/17565/10146097/ec1c6708-65f4-11e5-829a-ce05206a1476.jpeg)

There we go. PR incoming.

**Comment by annegentle** [comment]
Mike and I tested with v4 client and still have this problem.

**Comment by smashwilson** [comment]
Mike's problem was different: he had local modifications to his nexus-control repository, which most likely had his repository half-mapped (meaning it was in `content.json`, but not in `routes.json`).

What repository are you looking at? Can you verify that your nexus-control repository is up to date and on its `master` branch?

**Comment by annegentle** [comment]
Verified this morning with updated nexus-control repo, closing. Thanks! :sparkle:
