### ISSUE TITLE
Usability: Once you build with one template, cannot switch to a different template by editing

### ISSUE THREAD

**Issue by annegentle** [deconst/deconst-docs#171]
Expect result: When you click edit on a content repo build that has already run, want to choose a different template from the dropdown menu.

Actual result: With a docs-container-service content repo already building, click edit, then try to choose another template. Message under Template section says "No templates to choose from, yet. Please specify both a control and a content repository."

Screenshot:
<img width="712" alt="screen shot 2015-09-28 at 1 32 21 pm" src="https://cloud.githubusercontent.com/assets/501981/10144874/a2ac7b3a-65e5-11e5-8de2-0132557496c1.png">

**Comment by smashwilson** [comment]
As a temporary workaround, if you delete and re-type in any of the other input fields, the validation fires again and you can see the template selection.

**Comment by smashwilson** [comment]
But the real fix will be in the next release :wink:
