### ISSUE TITLE
Process for adding new content

### ISSUE THREAD

**Issue by meker12** [deconst/deconst-docs#173]
When you want to add a new product or book to Nexus:

Step 1: 
A PR against the nexus-control repo to add the route.

Step 2:
A PR against the QuickStart repo to add the link to the Docs landing page. 

Step 3:  
???   Does Engineering have to run any scripts or restart the server for the changes to take affect as soon as the PRs are merged? 

Noting that the PR would be done by the Coordinator -- I think that is Anne now?

I do see the documentation here:  https://github.com/deconst/deconst-docs/blob/master/writing-docs/coordinator/mapping.rst

So if this is still a manual process,  how do we communicate that something needs to be added/deleted?

**Comment by smashwilson** [comment]
See #135 for details about adding new content repositories (product, book); see #134 for details about making control repository changes take effect.

> ??? Does Engineering have to run any scripts or restart the server for the changes to take affect as soon as the PRs are merged?

Only for the PR against the control repository, but that's one more than what I'd like to have!

> I do see the documentation here: https://github.com/deconst/deconst-docs/blob/master/writing-docs/coordinator/mapping.rst

http://deconst.horse/writing-docs/coordinator/mapping/ is actually out of date, I'm afraid. There was a rather large refactoring that the docs have been lagging behind... the concepts are still accurate, but the syntax and the file structure are all off.

> So if this is still a manual process, how do we communicate that something needs to be added/deleted?

For now, I'd open an issue on the nexus-control repository (or send a pull request to add the content to the [content map](https://github.com/rackerlabs/nexus-control/blob/master/config/content.json) and [routes map](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.json)), and we can coordinate from there.

**Comment by smashwilson** [comment]
How many more of these will you need to add in the next few months?

I have a few scripts and utilities that I wrote to make adding the last 18 more tractable.

**Comment by smashwilson** [comment]
Now that we have self-hosted builds, this is a lot easier! In a nutshell:
1. Give @rackernexus access to your repository
2. Put a `_deconst.json` file in each Sphinx/Jekyll directory
3. Add a line to `content-repositories.json` in the control repository

The Deconst documentation [goes into more depth on some of this](https://deconst.horse/writing-docs/author/#adding-a-new-content-repository).
