### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#18]
We need to whip up some kind of logo for this thing.

Any ideas?

**Comment by chesshacker** [comment]
This logo will replace the default GitHub avatar for our deconst project.
As we discussed in Slack, I will ask Jonathan Stovall to take a shot at this when he gets back from SXSW on Monday.  Something that "evokes writing"... or whatever idea comes to him.

**Comment by rgbkrk** [comment]
:notebook_with_decorative_cover:

**Comment by smashwilson** [comment]
Oh yeah, we Jonathan got this to us a while go. I'm a fan :grin:

**Comment by rgbkrk** [comment]
Yeah it's pretty slick.
