### ISSUE TITLE
The control preparer exited with status 185.

### ISSUE THREAD

**Issue by j12y** [deconst/deconst-docs#185]
I'm still investigating and will add more details or close/resolve as I learn what the issue is.

I'm trying to add **support.rackspace.com** to nexus.  I've forked nexus-control with my settings local and have a basic `jekyll new` repos as a starting point.  Once added to the deconst client I get an error.

`
The control preparer exited with status 185.
`

Likely I'm missing some simple step in setting things up that I didn't get the right dependencies...

```
$ docker logs -f preparer-control-1
npm WARN package.json Dependency 'cheerio' exists in both dependencies and devDependencies, using 'cheerio@^0.19.0' from dependencies
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.3.5
npm WARN optional dep failed, continuing errno@0.1.4
npm WARN optional dep failed, continuing mkdirp@0.5.1
npm WARN optional dep failed, continuing request@2.65.0
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.3.5
npm WARN optional dep failed, continuing errno@0.1.4
npm WARN optional dep failed, continuing mkdirp@0.5.1
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path ../rimraf/bin.js
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../rimraf/bin.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/control-repo/npm-debug.log
```

**Comment by smashwilson** [comment]
Ah - @jnoller hit that one, too. As I recall, it was a problem with his specific version of VirtualBox. Try upgrading VirtualBox and giving it another shot.

**Comment by j12y** [comment]
I'm on 5.0.4 r102546 

Checking for updates says I'm on the latest, but there seems to be a 5.0.8.
https://www.virtualbox.org/wiki/Downloads

I'll give it a shot.

**Comment by j12y** [comment]
Not sure if it was updating or cycling everything, either way that seemed to do the trick.  Thanks Ash!

**Comment by smashwilson** [comment]
:+1: Awesome! Yeah, we've hit our share of weird VirtualBox edge cases with this thing.
