### ISSUE TITLE
Full-text search

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#187]
Enabling search across all Deconst-indexed content has been a major goal of this project since we started it back in March, but for some reason we never made a proper issue for it. We already have an Elasticsearch instance in place within our architecture for log aggregation, so it's a question of correctly storing content as it arrives, extending the content service API with endpoints to support search, then consuming them within the presenter to provide a place for sites to hook in search queries and results.

**I. First, we'll need to index incoming metadata envelopes in Elasticsearch.** This could be as simple as jamming them as-is into Elasticsearch, but I'm guessing that we'd get better results if we mutate them somewhat for optimal indexing. I predict many trips to [the Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html).
- Do we need to scrub HTML markup from the body before indexing?
- We should support some kind of well-defined "meta" tags for explicit keyword indexing. We could use these for SEO, then, too.
- We'll need to be certain that we delete stale information from the search index when new content arrives with the same ID.

**II. Then we need to design a content service API to submit searches and retrieve results.** We _could_ accept Lucene queries and pass them directly to Elasticsearch, but once again, I suspect that there's a better way.
- Search results will be returned in terms of content IDs, because the content service has no knowledge of the control repository.
- We'll likely want to include additional information about each match, like preview snippets with offset data to highlight matching text.
- Ordering of search results is important. I'm guessing that Elasticsearch will give us the knobs to tune this to get it to the way we want, but we'll need to know what the way we want is, first.
- We may want the ability to optionally constrain results to results from a specific domain.

**III. Finally, we need to figure out how to render search results within a page.** This is a little more involved than it seems because the content service talks entirely in terms of content IDs, while to be useful we need search results as presented URLs. I can see two possible directions:
1. Flag certain pages as "search result pages" somehow (in the control repo, possibly?). Nab standard query flags from URLs on those pages (`?q=term&page=3&perPage=10`) and submit a query to the content service. Translate result objects from content ID to presented URL based on the current content mapping. Then, either: _(a)_ inject the result objects into the envelope's body HTML with a content filter, or _(b)_ make the result array available to the nunjucks templates as a variable.
2. Expose a _presenter_ API endpoint that fires queries to the content service, maps the content IDs, and returns results as a JSON object. Consume it entirely from client-side Javascript. This would make it somewhat more difficult to incorporate within each domain, but it would let us do things like implement a loading spinner while the search is being done.

I don't really have any experience designing search systems, so any input from those who do is most welcome :bow:

@steveortiz, @j12y: Please weigh in if the KC has any additional requirements for this.

/cc @kenperkins @jnoller

**Comment by smashwilson** [comment]
@ktbartholomew: No rush on a reply -- I know you're busy with other stuff and there are a few other annoyances I'd like to address before I start :wrench: on this in earnest --  but I'm curious if you have an opinion about which way we should go for section III up there.

**Comment by ktbartholomew** [comment]
I think we should implement this as another presenter template API, so that we're not limiting what implementers can do with the search experience. There may be many templates within a site that surface search results or search tools. We can also leverage the existing request API to allow flexibility on query string parameters, although falling back to `?q=` is probably a good default.

This would also allow us to reverse-lookup the presented URL from the content ID within Node, where it's pretty easy to do. I'm pretty sure I already wrote code to do that somewhere else in the presenter, so this is mostly a matter of making that more consumable as a general service.

```
{% set searchResults = deconst.search.getResults({query: deconst.request.query.q}) %}

{% for result in searchResults %}
  {{ result.url }}
{% endfor %}
```

**Comment by smashwilson** [comment]
> I think we should implement this as another presenter template API, so that we're not limiting what implementers can do with the search experience. There may be many templates within a site that surface search results or search tools.

Yeah, that makes total sense to me :+1:

**Comment by ktbartholomew** [comment]
Seems like Javascript-y search could also be done by creating a presenter template like this:

```
{{ deconst.response.set('Content-Type', 'application/json') }}

{{ deconst.search.getResults({query: deconst.request.query.q})|json }}
```

**Comment by j12y** [comment]
> We may want the ability to optionally constrain results to results from a specific domain.

This came up the other day for supporting faceted search of KC content along lines of a product, etc. not even just limited to a specific domain.

**Comment by smashwilson** [comment]
[elasticsearch researching intensifies]

**Comment by smashwilson** [comment]
Hah. Yes, it looks like I'm going to need to preprocess HTML out of content as it's indexed. Otherwise we get "matches" in things like href ids:

``` json
{
  "results": [
    {
      "contentID": "https://github.com/rackerlabs/docs-container-service/docs/best-practices/container-technologies-registration-discover",
      "title": "Introduction to container technologies: registration and discovery of container services",
      "excerpt": " Email &amp; Apps.</p>\n\n<h3 id=\"<em>consul</em>-from-hashicorp\"><a class=\"anchor-link\" href=\"#<em>consul</em>-from"
    }
  ]
}
```

Not to mention excerpts that include partial or broken markup. Fortunately even full reindexes are pretty trivial, even in production right now.

**Comment by smashwilson** [comment]
Another enhancement we need: a metadata envelope key to explicitly exclude a document from search indexing. I've seen the `atom.xml` file show up in results already which seems like a bad idea.

**Comment by smashwilson** [comment]
@ktbartholomew: How's this for a template API?

```
{% for result in deconst.request.query.q|search %}
url {{ result.url }}
title {{ result.title }}
excerpt {{ result.excerpt }}
{% else %}
no results
{% endfor %}
```

With custom pagination:

```
{% for result in deconst.request.query.q|search(deconst.request.query.page, deconst.request.query.perPage) %}
```

Custom filters look fairly simple. The other major options are to implement a custom async tag, which is more involved and basically involves writing parser code, or cheating and kicking off a search every time a `q` parameter is seen (and hardcoding that and the other query parameters used for search).

**Comment by ktbartholomew** [comment]
@smashwilson :+1: That looks fine to me. It seems a little weird to have to use a filter to get search results, but I think Nunjucks handles async filters much better than it would async function calls, so it's fine by me.

Would there be a need to make the results a property of what's returned from the search filter? I'm thinking of an situation where we want to surface information about the overall search:

```
{
  "query": "Uniqorns",
  "suggested_query": "Unicorns",
  "total_results": 1000001,
  "results": []
}
```

However, if data like this isn't readily accessible from ES, then it's probably not worth over-architecting right now.

**Comment by smashwilson** [comment]
> Would there be a need to make the results a property of what's returned from the search filter?

Yeah, I actually just realized that myself. Elasticsearch returns the total number of results, which I'm [already exposing in the result object](https://github.com/deconst/content-service#get-searchqtermpagenumbernumperpagesize), so that you can know how many page links to create.

**Comment by ktbartholomew** [comment]
Template-wise, it'd be much nicer to just loop through all the results and then have a separate bit of logic to determine how many pages are in the total set.

**Comment by smashwilson** [comment]
Yeah, so like this:

```
{% set r = deconst.request.query.q|search %}

Result count: {{ r.total }}

{% for result in r.results %}
url {{ result.url }}
title {{ result.title }}
excerpt {{ result.excerpt }}
{% else %}
no results
{% endfor %}
```

**Comment by smashwilson** [comment]
Almost done; I just need to write up some docs for [deconst.horse](https://deconst.horse). I should be able to :shipit: tomorrow.

Before we start using it on any "real" sites, I'll want to implement a search page for the docs site and work out any kinks that manifest there.

**Comment by smashwilson** [comment]
I have a [search page for deconst.horse](https://deconst.horse/search/?q=control%20assets).

I'm investigating why it doesn't seem to be rendering with assets. Also, you'll notice that the result count is off; that's because I have unmapped metadata envelopes stored in that content service, which are trimmed out before the results are rendered.

The asset issue is one that I do want to address before we ship this to the other clusters, but the unmapped envelope issue shouldn't matter, especially once I get #133 working properly.

**Comment by smashwilson** [comment]
The search page now has assets:

![screen shot 2015-12-03 at 8 36 25 am](https://cloud.githubusercontent.com/assets/17565/11561980/f95c4528-9998-11e5-98d6-b2374ac6c687.jpeg)

**Comment by smashwilson** [comment]
Unsearchable documents are now supported.

One last feature before I mark the initial implementation as shipped: constraining search pages to specific properties.

We already have "tags" and "categories" (and now "keywords"), so I'd rather not introduce Yet Another Tagging Mechanism for this. Offhand I think I prefer using "categories", because those are intended to be fairly constrained, as opposed to "tags" which are more ad-hoc and open to machine-driven inferences and such. While I'm at it I'll separate deconst categories from Jekyll categories (although I'll derive the former from the latter) so we don't generate bogus category pages in docs-developer-blog.

**Comment by smashwilson** [comment]
Tentative API for the search filter:

```
{% set r = query.q|search(["developer.rackspace.com", "support.rackspace.com"], 2, 20) %}
```

... assuming Nunjucks supports arrays and String literals like that.

**Comment by smashwilson** [comment]
Actually I'm going with keyword arguments for Maximum Flexibility :tm::

```
{% set r = query.q|search(categories=["developer.rackspace.com", "support.rackspace.com"], pageNumber=query.page) %}
```

**Comment by smashwilson** [comment]
Category-constrained search is live and :rocket: as I type. To take advantage of it:
- Add categories to the content you want to search. The most convenient way to do this is to add something like this to your `conf.py`:
  
  ``` python
  deconst_categories = ['deconst.horse']
  ```
  
  or to your `_config.yml`:
  
  ``` yaml
  deconst_categories:
  - deconst.horse
  ```
- Pass one or more categories to the search filter in your Nunjucks template:
  
  ```
  {% set r = query.q|search(pageNumber=query.page, categories=["deconst.horse"]) %}
  ```

**Comment by smashwilson** [comment]
Now that an initial implementation of this is live, I'm going to close this mega-issue. I expect there will be a long tail of improvements that we can make to the indexing and searching process; I already have a few follow-on issues for quasi-related things that I found while I was poking around with this.

[File me issues](https://github.com/deconst/deconst-docs/issues/new) for anything more specific that any of you dig up and we'll go from there.

:checkered_flag:
