### ISSUE TITLE
Docker Compose setup for development

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#19]
I'd love to have a [docker-compose](https://docs.docker.com/compose/) setup for development that launches the entire system as an interconnected, self-sufficient set of containers on your local system. You should be able to run:

``` bash
docker-compose up -d
```

And then be able to submit content by running the preparers locally, as:

``` bash
mkvirtualenv deconst-preparer-rst --python=$(which python3)
pip install -e git+https://github.com/deconst/preparer-rst.git#egg=deconstrst
cd ${DOCDIR}
export CONTENT_STORE_URL=http://$(boot2docker ip):9999/
export CONTENT_ID_BASE=https://github.com/...

deconst-prepare-rst
```

Where should the docker compose configuration live, though?

**Comment by rgbkrk** [comment]
omni-deconst

**Comment by smashwilson** [comment]
I'm just using this repo itself, because it's convenient and we're already using it for other "meta" things.
