### ISSUE TITLE
Move api.rackspace.com to Nexus

### ISSUE THREAD

**Issue by chesshacker** [deconst/deconst-docs#209]
After the moratorium, we would like to shut down the current api.rackspace.com website.  I think it makes sense to redirect anyone who visits api.rackspace.com to developer.rackspace.com/docs.  To do this, we could update the DNS so api.rackspace.com goes to Nexus, and that redirects the user.

**Comment by chesshacker** [comment]
@smashwilson: do you think we could make this change in January?

**Comment by annegentle** [comment]
Is it possible to do slightly more fine-grained redirects such as to the service page rather than api landing page to docs landing page?

**Comment by smashwilson** [comment]
In terms of Deconst work, certainly: we'd only need to add a [section to `config/rewrites.json`](https://github.com/rackerlabs/nexus-control/blob/master/config/rewrites.json#L119-L128) in the control repository for this to happen. You wouldn't even need me for that bit at all, it's just a PR to nexus-control, and it'd go live shortly after merge.

The most annoying bit will be getting the TLS certificate re-issued with new SANs. We could add `launch.rackspace.com` and a few `www.` variants while we were at it, though.

> Is it possible to do slightly more fine-grained redirects such as to the service page rather than api landing page to docs landing page?

Yes, although it would be more tedious. Do we have a full map of api.rackspace.com to use as a reference?

**Comment by annegentle** [comment]
There's not a lotta files, here's the list :)

api-ref-auto-scale.html
api-ref-backup.html
api-ref-big-data.html
api-ref-blockstorage.html
api-ref-databases.html
api-ref-email-and-apps.html
api-ref-files.html
api-ref-identity.html
api-ref-images.html
api-ref-keep2.html
api-ref-monitoring.html
api-ref-networks.html
api-ref-orchestration.html
api-ref-queues.html
api-ref-servers-ext.html
api-ref.html

I can write the PR for the `config/rewrites.json` and you can choose to merge after January, would that work?

**Comment by cyrichardson** [comment]
Rackspace CDN - file name ﻿api-ref-raxCDN.html, I think -  is also in the API reference and should be added to Anne's list above. (api-ref-raxCND.xml is definitely in the source at https://github.com/rackerlabs/docs-api-reference/tree/master/api-ref/src/docbkx.)
Thanks!

**Comment by annegentle** [comment]
also these: 

api-ref-raxCDN.html
api-ref-big-data-v2.html

**Comment by annegentle** [comment]
@smashwilson can this issue be closed or do we need to wait on the certs?

**Comment by smashwilson** [comment]
@annegentle I've been trying to chase down the new certs for a week now. Just waiting on Thawte to re-issue with the new SANs. Let's keep this open until I get ship them.

**Comment by kenperkins** [comment]
From what I can tell, the certs have had `api.rackspace.com` added, but requests to that domain still route to the old servers. I'll figure out how to get those decommissioned, and then update the corporate DNS entry for api.rackspace.com -> deconst.

**Comment by kenperkins** [comment]
I've made a request to have the DNS changed. @annegentle do you know who owned/managed the internal infra for api.rackspace.com?

**Comment by annegentle** [comment]
I think it must be @steveortiz and crew?
