### ISSUE TITLE
Service registration and discovery with etcd

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#23]
Rather than pass URLs around in environment variables, I'd love to start using etcd for service registration and discovery.

This will take some research on my part, first.

**Comment by jrperritt** [comment]
Bumping to Milestone v0.2 to help address #8

**Comment by jrperritt** [comment]
The service discovery and registration should be easy enough once we want to have a cluster. Using etcd as a central store is a bit trickier if we want the services updated on changes like the `mapping-service` and `layout-service` are currently handled when a control repo changes. If we just want to pull the relevant values from etcd on start-up, then that would be easy to do. Otherwise, we'd need watchers for every environment variable we want to track. The way environment variables are currently being handled, a change to one would require a service restart anyway.

**Comment by smashwilson** [comment]
When I wrote this, I was mentally planning to have an architecture where we would hide the containers of each service behind a load balancer, and the CLB's hostname would be what was registered in etcd:

![individual-clbs](https://cloud.githubusercontent.com/assets/17565/7597583/76feb4de-f8c2-11e4-92af-f5926ed944a8.png)

In this scheme, the CLB for each service family would be what we'd register in etcd. The main benefit to using etcd here would be that we could have Ansible do things like launch a new herd of containers on a new host, provision a new CLB and register all of them with it, update the etcd key to point to the new CLB, and kill the old one to manage upgrades - the upstream services would pick up the etcd change and direct traffic to the new services without needed a redeploy. (We could also do this by draining connections from the CLB itself, though. Hmm.)

Now I'm thinking of doing something simpler:

![service-pods](https://cloud.githubusercontent.com/assets/17565/7597659/f898eaf0-f8c2-11e4-80e3-2a91d636dfd2.png)

Each service pod is a self-contained set of containers that reside on the same host and communicate among themselves via container links. My main motivation for doing this is to keep communications among services within a pod as quick as possible. We _do_ lose the ability to scale individual services independently if they become bottlenecks, though.

I think the etcd service registration would be helpful for the original architecture, but unnecessary for the pod-based one.

Am I making sense? Which approach do you like better?

**Comment by jrperritt** [comment]
Yep, I think that makes perfect sense. Would each pod be on its own VM? Originally I was picturing diagram 1 in my head, but I think I like diagram 2 better. If we need individual services to scale, we can combine the 2 diagrams by increasing the number of containers for the bottle-necked service and putting a load balancer in front of them and inside the pod. The presenter wouldn't need to track URL changes since all the resources would be local. It seems like only communicating with local resources greatly reduces complexity (such as additional interaction with etcd) and is a win.

**Comment by smashwilson** [comment]
On reflection, I should really break this out into its own separate issue. Either way we go it's the first thing I was going to tackle once I got back to the Ansible stuff.

> Would each pod be on its own VM?

I was picturing that we would have several pods on each VM and never break a pod across VM boundaries. That way, we don't need to introduce anything like weave or flannel to link containers within each pod.

We can tune the number of pods per VM based on system metrics. I'm kind of expecting the retrieval from Cloud Files to dominate our total render time (based on no data whatsoever), which would mean that most of our time would be spent waiting for the content-service to complete external IO, and we could host many pods on each VM without too much trouble. If it turns out that something like the handlebars rendering dominates instead, say, then we're going to be more CPU-bound and probably capped at one pod per vCPU.

> If we need individual services to scale, we can combine the 2 diagrams by increasing the number of containers for the bottle-necked service and putting a load balancer in front of them and inside the pod.

True! I'd rather use vulcand or nginx as an internal load balancer just to keep everything inside the host, but that would probably work pretty well.

> It seems like only communicating with local resources greatly reduces complexity (such as additional interaction with etcd) and is a win.

Yeah, that's what I was thinking too :+1:

**Comment by jrperritt** [comment]
> I was picturing that we would have several pods on each VM and never break a pod across VM boundaries. That way, we don't need to introduce anything like weave or flannel to link containers within each pod.

OK. I definitely agree with not breaking a pod across VM boundaries. When I was (briefly) thinking about multiple pods vs one pod per VM, the only question I had with having several pods per VM is the port scheme. I think currently each pod requires 5 unique ports. The number of ports wouldn't be an issue, but tracking which pods have which ports may be tricky. That may not be an issue, but it's something that came to mind. Regardless, after thinking about it some more, whatever that entails is probably better than wasting resources with 1 pod per VM.

> True! I'd rather use vulcand or nginx as an internal load balancer just to keep everything inside the host, but that would probably work pretty well.

Agreed

**Comment by jrperritt** [comment]
In light of the new architecture, I think we can close this.
