### ISSUE TITLE
GitHub links for deconst-docs

### ISSUE THREAD

**Issue by meker12** [deconst/deconst-docs#232]
Does the deconst-doc repo support "Submit an issue" or "Edit on GitHub" links.  If so, I'd be happy to submit the PR to configure one or the other.

**Comment by smashwilson** [comment]
It depends on what you mean by "support." :grin: We'd need to add it to the [templates in the control repository](https://github.com/deconst/deconst-docs-control/tree/master/templates/deconst.horse) first, but it could be done.
