### ISSUE TITLE
Put a load balancer in front of each presenter

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#24]
I'd love to start using [vulcand](https://vulcand.io/) as a reverse proxy so that we can start sharding services across multiple containers.

**Comment by smashwilson** [comment]
We can also terminate SSL at vulcand.

An alternative is using a Cloud Load Balancer.

**Comment by jrperritt** [comment]
Has a decision been made on vulcand vs CLB? If we decide on vulcand, we might as well do #23 too.

**Comment by smashwilson** [comment]
> Has a decision been made on vulcand vs CLB?

Nope. I keep going back and forth. They'll both let us add and remove nodes without downtime, which is the feature I want the most. I think vulcand will get us better TLS, but using CLBs would take a lot less work. I keep being indecisive, which is one of the reasons I haven't touched this :wink:

**Comment by kenperkins** [comment]
I don't think we can avoid CLB unless we've got floating ip.

**Comment by smashwilson** [comment]
Hmm. developer.rackspace.com is actually getting an A- from SSLLabs now - that's not bad. I'm okay with terminating TLS at a CLB, then.

**Comment by kenperkins** [comment]
It's not that I'm in love with CLB, it's just that we can't really do HA without floating ip, unless there's some swanky new development.

**Comment by smashwilson** [comment]
Yeah, so it's either (a) CLB or (b) CLB with a single node that talks to the active vulcand process. As much fun as vulcand would be to take for a spin, I'd prefer to err on the side of dogfooding and simplicity.

**Comment by jrperritt** [comment]
I think we now only need 1 load balancer that directs traffic to all the presenters. See #58

**Comment by smashwilson** [comment]
Done in deconst/deploy#17 :hammer:
