### ISSUE TITLE
Deconst doc site is down

### ISSUE THREAD

**Issue by meker12** [deconst/deconst-docs#247]

**Comment by smashwilson** [comment]
Looks like stale credentials somewhere:

![screen shot 2016-07-18 at 12 00 58 pm](https://cloud.githubusercontent.com/assets/17565/16921383/54bb47d0-4cdf-11e6-8747-53e302eab5d7.jpeg)

I'm on it. 🔧

**Comment by smashwilson** [comment]
It took a cluster rebuild, but we're [back up](https://deconst.horse/).

/cc @onthecly
