### ISSUE TITLE
Refactor common Python code into a shared module

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#26]
The mapping service and the layout service are likely to share a fair amount of logic: configuration from environment variables, setting up GitHub webhooks, things like that. We should make a module that both can import to keep code duplication under control.

**Comment by smashwilson** [comment]
This will let us solve #8 without annoying amounts of copy-paste.

**Comment by jrperritt** [comment]
Repo here: https://github.com/deconst/common-python

To use, add `-e git://github.com/deconst/common-python.git#egg=deconst_common` to `requirements.txt`.
