### ISSUE TITLE
"preparer" - Render .md to json

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#3]
Create a _renderer_ that builds [Jekyll](http://jekyllrb.com/) repositories containing Markdown files to our json schema.

**Comment by smashwilson** [comment]
By the way, this is necessary to support moving forward because the [blog posts](https://github.com/rackerlabs/developer.rackspace.com/tree/master/src/site_source/_posts) are all in Markdown. :point_up:

**Comment by rgbkrk** [comment]
Perhaps this [JSON renderer for Jekyll](https://github.com/benbalter/benbalter.github.com/blob/0db7c54b44eaccf146c2b2f520eee3e8175560bb/_plugins/generate-json.rb) will be of some help.

**Comment by smashwilson** [comment]
The [Jekyll preparer](https://github.com/deconst/preparer-jekyll) is now a thing that exists. It uploads conforming metadata envelopes and assets to the content service. :notes:
