### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#30]
We currently have very few unit tests for, well, anything, which isn't generally how I roll. I should go back and retrofit some simple tests for different services.

**Comment by smashwilson** [comment]
@kenperkins: What's your favorite JavaScript test framework? I've used Jasmine and (briefly) QUnit.

**Comment by kenperkins** [comment]
Typically Mocha has had the most traction. I've used it a lot. It's not perfect, but it gets the job done.

**Comment by smashwilson** [comment]
Works for me.

**Comment by smashwilson** [comment]
We now have unit tests for everything except the preparers. :confetti_ball:
