### ISSUE TITLE
Measure and load-test response times

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#37]
Simulate some degree of traffic and make sure that deconst can handle the load.

**Comment by kenperkins** [comment]
do we think this has to use some kind of realistic traffic distribution? or can we just hammer on it with `ab` or something similar?

**Comment by smashwilson** [comment]
No idea.

The main things that I'd want to get out of these metrics are:
1. How do changes that we make to our code and infrastructure change performance and scalability?
2. How does deconst compare to the existing developer.rackspace.com infrastructure? I'm expecting that we'll take a performance hit (we're not going to beat nginx serving a static file) but I'd like to use that as a baseline for comparison.

To those ends, I think we'll need to track two metrics:
1. Render times for each page (probably average and quartiles)
2. Number of simultaneous requests that we can handle

**Comment by smashwilson** [comment]
Eventually, we'll want to collect live metrics on the deployed site, too. I was thinking about integrating statsd to cheaply collect a bunch of performance data while we run. This issue is more about having a benchmarking suite we can use to hammer a staging server with to see how a deployment is about to change our bottom line.

**Comment by kenperkins** [comment]
we can probably approach Nginx through in-app caching. It's not like we expect content to change with a high frequency.

**Comment by smashwilson** [comment]
Reasonable. That's exactly the kind of optimization I'd like to have metrics in place before implementing, though :grin:

**Comment by kenperkins** [comment]
![image](https://cloud.githubusercontent.com/assets/730664/7885220/7f48a894-05d7-11e5-88f7-5361b4da38d2.png)

**Comment by smashwilson** [comment]
Pretty reasonable :clap: That's not even with the servicenet changes this morning from deconst/content-service#38 and deconst/deploy#32.

I did add certs to the CLB. Care to re-test? Although, if the differences between nginx and deconst are dwarfed by TLS negotiation, I'll be pretty happy.

**Comment by kenperkins** [comment]
After editing `/etc/hosts`:

![image](https://cloud.githubusercontent.com/assets/730664/7890788/fc76dbf4-05fc-11e5-8253-53ba8ca3fd8a.png)

**Comment by smashwilson** [comment]
:+1: Good enough to launch, I'd say. :rocket: :shipit: :guitar:
