### ISSUE TITLE
"mapping service" - Map paths to content IDs

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#4]
Create a service that maps paths within a deconst domain to a content ID and a subpath. For example: `"developer.rackspace.com/quickstarts/ruby/compute"` might map to `("https://github.com/rackerlabs/docs-sdk-ruby/trees/staging", "/compute")`. Some paths may be mapped to a redirection to a different path. Others may map to a hostname and port within the cluster.

**Comment by smashwilson** [comment]
Note that this is a _little_ different than what we'd talked about before. I think it'll be a bit easier for the presenter to use if the mapping service returns a tuple like this, because it can translate it into _Cloud Files container_ and _path within that container_ more directly.

Also, I was wondering if we should make the content IDs more "git-aware", specifically by directly calling out the ref that's tracked as a separate thing. On the other hand, I quite like the idea of having them just be plain old URLs, and of having them be something you can paste into your browser to see the content it's derived from right there.

**Comment by rgbkrk** [comment]
I'd like to be more git aware too.

**Comment by kenperkins** [comment]
I'm a little confused on the value of `/compute` on the example above.

**Comment by smashwilson** [comment]
Ah, this is out of date. I had a different picture in my head when I wrote the issue description. Really, this should just map presented URLs to content IDs, which we can then fetch from the content service:

> `developer.rackspace.com/quickstarts/ruby/compute` might map to `https://github.com/rackerlabs/docks-sdks/trees/staging/compute`

**Comment by kenperkins** [comment]
So no longer a tuple, which is what I was confused on.

**Comment by smashwilson** [comment]
Correct. As far as I know.

I don't know if we had decided to keep the mapping files for all domains in a common map repository, or have a separate map repository for each domain.

**Comment by smashwilson** [comment]
Done in [mapping-service](https://github.com/deconst/mapping-service) and [on DockerHub](https://registry.hub.docker.com/u/deconst/mapping-service/). :sparkles:
