### ISSUE TITLE
Content tags

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#41]
The Jekyll blog index layout uses Liquid tags to generate the blog index:

``` html
<!-- _layouts/category_index.html -->
<ul class="blog-entries">
  {% for post in site.categories[page.category] %}
    <li class="entry">
      <span class="byline"> {{ post.date | date_to_html_string }}</span>
      <h2 class="title"><a href="{{ post.url }}">{{ post.title }}</a></h2>
      <div class="categories">Filed under {{ post.categories | category_links }}</div>
     </li>
   {% endfor %}
 </ul>
```

This logic probably belongs in a presented page rather than a layout, but we'll need to use Handlebars magic and some content service help to make it work. I'm thinking:
- Add tags to the metadata envelope specification. Index on them in Mongo.
  
  ``` json
  {
    "title": "one",
    "body": "..",
    "tags": ["foo", "bar", "baz"]
  }
  ```
- Allow a metadata envelope to request the inclusion of related content by tag by including a special key.
  
  ``` json
  {
     "title": "two",
     "body": "..",
     "tags": ["index"],
     "include": { "tags": ["bar"], "max_results": 20 }
  }
  ```
- Use [`{{#each included}} ... {{/each}}`](http://handlebarsjs.com/builtin_helpers.html#iteration) within the Handlebars templates to process them.

**Comment by smashwilson** [comment]
Jekyll has both "tags" and "categories". Blog posts have categories, but I think any page can have tags. Do we want or need both concepts in deconst? Should I collapse them, or keep them separate?

**Comment by jrperritt** [comment]
If categories have more weight than tags, I think it would be useful to keep them separate for search purposes. For example, if a blog post has "Cloud Load Balancers" as a category, then that post is solely or mostly about CLBs. Alternatively, if a blog post mentions CLBs, it might have a CLB tag. 
If there's no weighting scheme like that, I'd say it'd be fine to collapse them to a single field.

**Comment by smashwilson** [comment]
I've kept them separate so far, to give us as much freedom as we can. I do like the idea of tags being machine-manipulated (inferred by LSI, normalized, and so on) while categories are explicitly provided.

**Comment by jrperritt** [comment]
:+1:  Additionally, if we do keep them separate, I think categories should be fixed and chosen from instead of free-entry. The control repo admin could add to the list of possible categories. That would prevent typos and give the categories consistency; Tags would be more granular.

**Comment by smashwilson** [comment]
> categories should be fixed and chosen from instead of free-entry. The control repo admin could add to the list of possible categories.

Fantastic idea :sparkles: Agree completely.

I'll probably start implementing this on Monday. It's one of the last functional blockers for 0.2!

**Comment by smashwilson** [comment]
## Stages
- [x] **content-service:** Store selected attributes from metadata envelopes in a MongoDB collection. Index them by category and tag. _Attributes to include:_ title, publish_date, tags, categories, content ID.
- [x] **content-service:** If a "query" directive is present in an outgoing metadata envelope, query Mongo for the appropriate documents and inject them into the content document.
- [x] **preparer-jekyll:** Pass a "query" directive from a document's frontmatter to the generated envelope.
- [x] **mapping-service:** Support inverse queries for the presented URL that maps to a given content ID.
- [x] **presenter:** If a "query" directive is present in the metadata envelope, make additional calls to the mapping service to generate the corresponding presented URL of each.
- [x] **documentation:** Bring the metadata envelope schema and example up to date (along with new attributes from #43).

Locking down categories to a set list should be done as part of metadata envelope validation (which we don't have in place yet). It also means that the content-service will need to pull and refresh the control repository, too.

**Comment by smashwilson** [comment]
The blog index now renders properly. :sparkles:
