### ISSUE TITLE
Aggregate and manage logs and statistics

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#42]
We've got a bunch of microservices, all producing a ton of logs. We want to be able to maintain basic situational awareness across the site, including:
- Real-time performance, rendering and request times
- HTTP status codes
- Exceptions and stack traces on whatever

Helpfully, docker 1.6.0 just added [logging drivers](https://github.com/docker/docker/blob/master/CHANGELOG.md#160-2015-04-07) to do things with container logs other than "write them to the filesystem as giant JSON files." Notably, there's a syslog driver.

Sounds like a great excuse to add an ELK stack to the deployment to me.

**Comment by smashwilson** [comment]
Helpfully, there's an [Ansible galaxy role](https://galaxy.ansible.com/list#/roles/1243) for an ELK stack, because of course there is.

We'll want Cloud Monitoring on all the things as well.

**Comment by jnoller** [comment]
For elk we're going to want to run on onmetal - elastic search doesn't like cloud things

**Comment by kenperkins** [comment]
Please consider realtime `tail -f` and `grep` of aggregated logs as a use case for this feature :)

**Comment by smashwilson** [comment]
I'll need to wait for ansible/ansible-modules-core#1405 to be able to configure the containers with Ansible. Alternately, if #86 pans out, we might not have to wait.

**Comment by smashwilson** [comment]
:bookmark:  A relevant [StackOverflow question](http://stackoverflow.com/questions/23082512/coreos-systemd-journal-remote-logging) for bridging the gap from journald on a CoreOS host to logstash.

**Comment by smashwilson** [comment]
ELK is live :sparkles:
