### ISSUE TITLE
HTML entities expanded in titles

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#44]
I'm not certain yet at what point in the pipeline this is being done, but HTML entities are being rendered as-is within page titles:

![screen shot 2015-04-22 at 8 43 32 am](https://cloud.githubusercontent.com/assets/17565/7274529/97dac514-e8cb-11e4-905b-314fc793a26c.png)

**Comment by jrperritt** [comment]
Is the title in the metadata envelope `SDKs &amp; Tools` or `SDKs & Tools`? If it's the latter, I think the double braces [here](https://github.com/smashwilson/deconst-drc-control/blob/master/layouts/drc/sdk-page.hbs#L4) and [here](https://github.com/smashwilson/deconst-drc-control/blob/master/layouts/drc/default.hbs#L6) might be causing this and, if so, changing to triple braces should fix it. Disregard if you've already tried that. If it's the former, we may have to decode it before handlebars renders it.

**Comment by smashwilson** [comment]
No idea :grin: I hadn't even started to look into this; I filed the issue as soon as I noticed it.

Yep, I bet your triple-brace fix is the problem. I think I still want to check out the metadata envelope format first, to make sure I understand what the Jekyll preparer is outputting.

**Comment by smashwilson** [comment]
Yeah, that was it. The title in the metadata envelope is `SDKs &amp; Tools`; Jekyll already escapes the HTML.
