### ISSUE TITLE
Choose a different key-value storage engine for metadata envelopes

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#47]
I defaulted to using MongoDB initially because I'd been using it for Strider (#1). It would make a lot more sense for us to use Elasticsearch for deconst state instead, because we're going to be using Elasticsearch to back our search functionality and our logs and metrics (#42) eventually anyway.
- [ ] Launch an ELK stack on OnMetal with the Ansible playbook.
- [ ] Store metadata envelopes in Elasticsearch from the content service.
- [ ] Also store global site asset URLs in Elasticsearch from the content service. (This is massive overkill, but so is MongoDB, so ¯_(ツ)_/¯)
- [ ] Update the architecture diagram accordingly.

**Comment by kenperkins** [comment]
I'm disinclined to use Elastic Search as a single data store for all of nexus. I've used search clusters enough times to know that invariably you have partitioning issues, or index rebuilding, or other management issues that bias me away from such scenarios.

Given that we already have an api, it should be straight-forward to lean on Cloud Files or Mongo for standard KV lookup scenarios, and leave Elastic Search for the search side.

Thoughts?

**Comment by kenperkins** [comment]
I should add, part of my reason for having two stores is that the site would be fully functional in KV scenarios even if search is degraded or not functional.

**Comment by smashwilson** [comment]
Thanks for weighing in -- I've been waffling around on this for a while now. I edged toward Elasticsearch (enough to file the issue) mainly because @jnoller made approving noises that way during the demo.

> Given that we already have an api, it should be straight-forward to lean on Cloud Files or Mongo for standard KV lookup scenarios, and leave Elastic Search for the search side.

Absolutely - we can shuffle this around as much as we want to without touching the rest of the system at all. :+1: This also means that we can try different things and _measure_ the actual impact on performance, too.

> I've used search clusters enough time to know that invariably you have partitioning issues, or index rebuilding, or other management issues that bias me away from such scenarios.
> 
> I should add, part of my reason for having two stores is that the site would be fully functional in KV scenarios even if search is degraded or not functional.

Hmm, reasonable. I had this big thing typed up about not introducing more complexity at the application layer but I think I talked myself around in the process.

How would you feel about using something specialized like Redis as a KV store, then?

**Comment by kenperkins** [comment]
I _love_ Redis. But it's really brittle when it comes to high availability. And I'm not sure Redis is a good idea for a content store where the number of documents will grow over time as it's an in memory store.

**Comment by kenperkins** [comment]
Is this really the 0.2 milestone?

**Comment by smashwilson** [comment]
Nah, you're right, it's probably not.

Also, now I'm thinking that Cloud Files is decent enough for the KV stuff after all. We should switch to using servicenet for the connection, but other than that, we could leave it until we have actual performance metrics to tell us whether or not it's performant enough.

**Comment by kenperkins** [comment]
I'm ok with using Cloud Files for KV until we have a better grasp on our needs. The only catalyst for change right now is that we're already using Mongo for some configuration data, as @smashwilson has previously mentioned.

**Comment by smashwilson** [comment]
I agree, let's just stick with Cloud Files.

**Comment by kenperkins** [comment]
Btw, on the subject of elastic search as your primary datastore: 

> Some people actually advocate using Elasticsearch as a primary data store; I think this is somewhat less than advisable at present. If you can, store your data in a safer database, and feed it into Elasticsearch gradually. Have processes in place that continually traverse the system of record, so you can recover from ES data loss automatically.

https://aphyr.com/posts/317-call-me-maybe-elasticsearch
https://aphyr.com/posts/323-call-me-maybe-elasticsearch-1-5-0

**Comment by smashwilson** [comment]
Yep :smile:
