### ISSUE TITLE
"presenter" - Present content to a user

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#5]
Zero-state component that accepts an HTTP request and assembles the page for the response. Here's the rough sequence of events it uses to do this:
1. Accept a request from a particular domain and path.
   
   ```
    GET /docs/cloud-servers/getting-started HTTP/1.1
    Host: developer.rackspace.com
   ```
2. Query the path mapping service (#4) to determine the content ID for this page.
3. _If not found_ render a 404.
4. _If a redirect_ perform a redirect to the target path.
5. Call the content service (#16) with the content ID to fetch the metadata envelope. _If not found_ render a 404. 
6. Determine the layout for this page.
7. Assemble the page content by combining the document with its layout.
8. Return content to the user.

**Comment by smashwilson** [comment]
I'm currently leaning toward using Node.js here: if we want it to be asynchronous, I'd rather develop in an  environment that's asynchronous throughout rather than one that has it bolted on.

**Comment by rgbkrk** [comment]
:+1: to that

**Comment by jrperritt** [comment]
I'll take a crack at this.

**Comment by smashwilson** [comment]
:metal: :bow:

**Comment by smashwilson** [comment]
@jrperritt got it off the ground and we now have the presenter up and running at https://github.com/deconst/presenter .
