### ISSUE TITLE
Script name seems inconsistent between preparers

### ISSUE THREAD

**Issue by kenperkins** [deconst/deconst-docs#52]
`deconst-prepare-sphinx`
`deconst-preparer-jekyll`

**Comment by smashwilson** [comment]
Yeah, they should both be `-preparer-` for maximum consistency. I'll need to change the `.travis.yml` build for deconst-docs to match.

**Comment by kenperkins** [comment]
see https://github.com/deconst/deconst-docs/pull/53 and https://github.com/deconst/preparer-sphinx/pull/20

**Comment by smashwilson** [comment]
:+1: Awesome, thanks!

**Comment by smashwilson** [comment]
That should take care of it. :sparkles:
