### ISSUE TITLE
Layout Service

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#6]
We need some way to handle layouts: the common chrome that surrounds and embeds the content for any particular page. There are many open questions about this right now.
- I'm not certain yet how complex our layout logic needs to be. The simplest case would be to have a single layout shared by all pages. More complicated cases would be allowing each page to choose its layout, probably decided in the page map, and allowing layouts to be nested or to inject content in various named slots of parent layouts. Personally, I'd prefer to start simple and build something only as complex as we actually need it to be.
- The format for the master layouts is a tricky question. Most documentation is being standardized as reStructuredText via Sphinx, but at least the blog will be in Markdown via Jekyll, which means that out of the box we need to support both Jinja2 and Liquid. The presenter (#5) doesn't actually care, because it only sees the standard json format, but local builds might - unless we use the presenter for local builds, too.
- If we do need to map layouts to pages, where is that done? Is it another service that maps content IDs to layouts, or is it done within the mapper (#4)?

**Comment by smashwilson** [comment]
As an initial cut, I'm going to use a hardcoded layout built into the presenter. We'll still need to decide what manages these later.

**Comment by smashwilson** [comment]
_Per a conversation with @jrperritt:_

Layouts need to be applied to individual pages, while the map repository only deals with content ID prefixes that generally map to an entire content repository. This means that we _can't_ just specify layouts in the map repository; instead, we need some mechanism to choose a layout within the metadata envelope itself. But, this could cause a disconnect, because the outer page chrome and navigation and so on needs to be chosen based on the domain to which a page belongs, and with the map repository, that could change without notice to the content repository.

What I'm thinking right now:
- Include a "layout key" as part of each metadata envelope, which is a general key: `blog-post`, `quickstart`, `api-reference`, something like that.
- Either a layout service or the mapping service maps general keys to a specific template based on the domain of the specific presented URL: a page marked `blog-post` on developer.rackspace.com uses the `drc-blog-post.hbs` template from the template library.

**Comment by kenperkins** [comment]
Just so I understand what you're saying, a map-service entry will map `developer.rackspace.com/docs/cloud-servers/api-guide->https://github.com/rackerlabs/cloud-servers-rst/index.rst` and then all children pages of that rst will be mapped implicitly as part of that repo preserving relative urls?

**Comment by smashwilson** [comment]
> Just so I understand what you're saying, a map-service entry will map developer.rackspace.com/docs/cloud-servers/api-guide->https://github.com/rackerlabs/cloud-servers-rst/index.rst and then all children pages of that rst will be mapped implicitly as part of that repo preserving relative urls?

For content repositories that contain .rst, yes; see #4 for the feature discussion, the [map-example documentation](https://github.com/deconst/map-example#map-repository-example) for the map repository format, and the mapping-service tests for samples of [how the map repository is parsed](https://github.com/deconst/mapping-service/blob/master/tests/test_map_parser.py) and [how the map is used](https://github.com/deconst/mapping-service/blob/master/tests/test_prefix_map.py).

We did this because, otherwise, there's a lot of overhead involved in adding a new page to any content repository - a content author would have to also add a line to the map repository for _every single page_. Mapping entire content repositories in like this lets you "mount" a content repository somewhere on the site, but still lets content authors add and shuffle pages freely and naturally within their own sections. It keeps a clean separation between the work done by a content author and the work done by a site admin.

One of the things that I'm debating here is whether or not to put layout data into the map repository somehow, too, or to keep it separate.

## Putting layout data in the map repository

**Pro:** Doing this keeps all of the "site assembly" data in one place, with one set of issues and PRs and so on.

**Con:** The map repository maps prefixes of presented paths to prefixes of content IDs, so it doesn't have the granularity necessary to map specific layouts to individual pages. This makes the problem of how to represent layout mappings more complicated.

**Con:** I want to keep the map repository format as simple as I can, so that (1) the "parser" can stay simple, (2) it's harder for people to "break the build", and (3) you won't need to know BNF to edit it properly. Adding in layout data will complicate that.

## Introduce a separate layout repository and layout service

**Pro:** Cleanly separates responsibilities among system components.

**Pro:** The map repository format can stay simple and the layout repository format can start simple.

**Con:** Splits site administration into _two_ repositories that you have to watch and PR and everything. This also introduces the possibility of the layout repository getting out of date with the mapping repository.

More Cons for the first option, but I think the Con for the latter is a bit more serious. Still pondering this. :thought_balloon:

**Comment by smashwilson** [comment]
Actually, there's a third option, now that I think about it: we can put layout data (and the layouts themselves) in _different files_ in the map repository, but parse and serve them from a new layout service. That keeps the architecture clean but doesn't introduce a new git repository that lets things get out of sync. Hmmm.

**Comment by smashwilson** [comment]
How's this for a layout file format:

``` ini
[developer.rackspace.com]
# All metadata envelopes that specify "layout: page" on developer.rackspace.com
# will use the "layouts/drc-page.hbs" layout in the map repository. Likewise,
# "layout: blog-post" will use "layouts/drc-blog-post.hbs".
page drc-page.hbs
blog-post drc-blog-post.hbs

# Now pages under /developer-blog that specify "layout: blog-post" will use
# "layouts/developer/blog-post.hbs", instead.
/developer-blog blog-post developer/blog-post.hbs

[data.rackspace.com]
# These specify the concrete layouts for pages rendered on data.rackspace.com.
page data-page.hbs
blog-post data-blog-post.hbs
```

**Comment by smashwilson** [comment]
Here's what I'm thinking for this after all of that:
- The layouts themselves (handlebars files) and the layout assignment data are managed in the **map repository**.
  - We'll need to introduce a filename pattern to distinguish mapping data from layout assignment data. Possibly `.map.txt` and `.layout.txt`?
  - We should probably rename the map repository to something else, because it isn't just being used for path mapping any more. I was thinking "control repository."
- Introduce a **layout-service** that accepts a presented URL and returns the layout to be used for that specific path.
  - Let's write this one in Python. It's likely to share code with the mapping-service - if not right away, then eventually.
  - Not Tornado though, because we aren't doing anything async (in either service). Flask maybe?

**Comment by smashwilson** [comment]
The layout service [now exists](https://github.com/deconst/layout-service). :sparkles: Thanks, @jrperritt!
