### ISSUE TITLE
Mount codebases as Docker volumes and enable auto-rerun

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#61]
To make day-to-day development with Docker more convenient, change the `docker-compose.yml` entries in each service repository that interacts with the control repository to mount the codebase as a volume, and enable live reloading for Restify / Express.js / Flask.

I'll need to make another change or two to get the layout and mapping services to gracefully use a mounted directory as a control repo checkout, too.
- [x] Content Service live reload
- [x] Presenter live reload
- [x] Webhook Service live reload
- [x] Mapping Service live reload
- [x] Layout Service live reload
- [x] Mapping Service local control repository
- [x] Layout Service local control repository

**Comment by smashwilson** [comment]
@kenperkins By the way, this issue will let us have our Docker cake and eat it, too. We can bundle all of our dependencies and such within the container, but still have rapid (either per-request or per-file-change) turnaround on previewing changes. :sparkles:

**Comment by kenperkins** [comment]
:heart:

**Comment by smashwilson** [comment]
Done across all services.

Live preview of control repo changes isn't quite there yet, but we're close.
