### ISSUE TITLE
handle known_hosts gracefully during deploy

### ISSUE THREAD

**Issue by jrperritt** [deconst/deconst-docs#67]
If a user deploy a deconst cluster and any of the servers in the cluster have an IP address that is already in the user's know_hosts file, the ssh to that host will fail.

**Comment by smashwilson** [comment]
[This bits](https://github.com/deconst/deploy/blob/master/provision.yml#L115-L131) handle trusting the SSH keys of newly-provisioned servers on launch. I'm not sure if it's 100% reliable, but it's worked for me on the last few cluster rebuilds, so I'll mark this done :+1:
