### ISSUE TITLE
Countdown to developer.rackspace.com

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#71]
Our goal is to deploy deconst as a backend for the existing developer.rackspace.com content. As far as I know, we're now feature-complete to do so.
- [x] Use `git subtree split` to divide the Jekyll and Sphinx content repositories from the [current developer.rackspace.com repository](https://github.com/rackerlabs/developer.rackspace.com).
  - We'll need to decide where to put these. Probably rackerlabs with some reasonable naming strategy?
- [x] Apply changes equivalent to the ones I made in the [control repository](https://github.com/smashwilson/deconst-drc-control), [docs repository](https://github.com/smashwilson/deconst-drc-docs), and [blog repository](https://github.com/smashwilson/deconst-drc-blog).
- [x] Include a README in each with instructions for fetching and merging new upstream content, so that we can keep the split repositories up to date with new blog posts or work performed during the transition period.
- [x] Provision a deconst cluster on the same account as the current developer.rackspace.com backend.
  - [x] Allow it to provision its own set of load balancers.
  - [x] Populate the `presented_url_domain` configuration value to let us see developer.rackspace.com content, even though the new load balancer even though DNS is pointing elsewhere.
- [x] Share the `credentials.yml` content securely with the rest of the team.
- [x] Ensure that Travis builds and webhooks are functional on the content and control repositories. Submit content from the content repositories.
- [x] Generate differences in content between the existing site and the deconst-hosted site. There will be some expected changes: deconst finally allows the quickstart guides to populate the page title, for example. This step may identify previously unknown content regressions.
- [x] Perform basic performance testing on the deconst-hosted site. Ensure that page response time will not suffer unduly in the transition, even under heavy traffic.
  - If it does, we can either increase the cluster size or introduce caching.
- [x] Add the deconst presenter services to the existing developer.rackspace.com load balancer. At this point, we will be dual-homed. Monitor the deconst nodes for errors.
- [x] Configure the new load balancers with the developer.rackspace.com TLS credentials.
- [x] Change the developer.rackspace.com DNS entry to point to the new load balancer. Verify that it propagates successfully. At this point, developer.rackspace.com will be purely deconst-hosted.
- [x] Destroy the old load balancer and other infrastructure.
- [x] Deprecate or delete the old, monolithic developer.rackspace.com repository.

**Comment by rgbkrk** [comment]
Will there be a 404 page across the sites?

**Comment by rgbkrk** [comment]
If I request a URL that doesn't exist, it gives back a 500 instead of a 404.

```
$ wget http://162.242.140.53/coolstuff
--2015-05-28 16:36:49--  http://162.242.140.53/coolstuff
Connecting to 162.242.140.53:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-05-28 16:36:49 ERROR 500: Internal Server Error.
```

**Comment by rgbkrk** [comment]
On a separate note, there appear to be unnavigable parts of our Jekyll blog categories...

```
--2015-05-28 16:35:53--  http://162.242.140.53/blog/categories/rails
Connecting to 162.242.140.53:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9865 (9.6K) [text/html]
Saving to: '162.242.140.53/blog/categories/rails'

162.242.140.53/blog/categories/rails  100%[=========================================================================>]   9.63K  --.-KB/s   in 0.001s

2015-05-28 16:35:53 (8.03 MB/s) - '162.242.140.53/blog/categories/rails' saved [9865/9865]

--2015-05-28 16:35:54--  http://162.242.140.53/blog/categories/cloud%20images
Reusing existing connection to 162.242.140.53:80.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-05-28 16:35:58 ERROR 500: Internal Server Error.

--2015-05-28 16:35:59--  http://162.242.140.53/blog/categories/custom%20images
Connecting to 162.242.140.53:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-05-28 16:35:59 ERROR 500: Internal Server Error.

--2015-05-28 16:36:00--  http://162.242.140.53/blog/categories/public%20cloud
Connecting to 162.242.140.53:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-05-28 16:36:01 ERROR 500: Internal Server Error.
```

**Comment by rgbkrk** [comment]
URLs don't get normalized. Is that ok? http://162.242.140.53/////blog/ --> Another 500/404.

**Comment by rgbkrk** [comment]
> Add the deconst presenter services to the existing developer.rackspace.com load balancer. At this point, we will be dual-homed. Monitor the deconst nodes for errors.

Love that idea. :smile:

**Comment by smashwilson** [comment]
> Will there be a 404 page across the sites?

Well, we apparently don't have one for https://developer.rackspace.com/ today:

https://developer.rackspace.com/flarp

We have the capability and should add one, but not before launch.

> If I request a URL that doesn't exist, it gives back a 500 instead of a 404.

This is related to :point_up:. Right now, if no layout is found for the _error page_, deconst defaults to rendering a 500 and a generic, hardcoded error page. Not great; we should preserve the original status code at least.

Can you open a separate issue for this one? I might not fix it pre-launch just in the interests of :shipit:, but I don't want to forget about it.

> On a separate note, there appear to be unnavigable parts of our Jekyll blog categories...

Nuts.

Are they navigable on https://developer.rackspace.com/ ? Is there an easy way that you can find a list of them? Pop me an issue about it either here or on [the docs-development-blog repo](https://github.com/rackerlabs/docs-developer-blog).

> URLs don't get normalized. Is that ok? http://162.242.140.53/////blog/ --> Another 500/404.

Weird. Yeah, they probably should. Open an issue here for it? (Noticing a theme, here? :wink:)

> Love that idea. :smile:

Right now it'll be pretty primitive (read: one step about `ssh` and `grep`). #42 is the issue for getting us proper log aggregation and search, and accordingly it'll be a high priority once we've shipped :smile:

**Comment by rgbkrk** [comment]
Reported several of the issues.

> (In response to unnavigable parts of the blog) - Is there an easy way that you can find a list of them?

Eh, I crawled the site and just skimmed through the status codes.

```
wget --wait=1 --limit-rate=400K -r -p -U "rgbkrk_spider" http://162.242.140.53/
```

Let me see if I can log those better.

**Comment by rgbkrk** [comment]
Ok, I have no idea where these are being found on the site:

```
--2015-05-28 21:04:01--  http://162.242.140.53/blog/categories/private%20cloud
Connecting to 162.242.140.53:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
```

but it seems like they have a "dash" counterpart

http://162.242.140.53/blog/categories/private-cloud

It's across a bunch of categories with spaces: 

``` bash
$ grep 'awaiting response' -B 2 wget.log | grep 500 -B 2 | grep 162 | grep -v connected | grep -v 'using existing connection' | grep -v "try:" | grep categories | cut -c 47- | sort | uniq
/blog/categories/application%20deployment
/blog/categories/assistive%20technologies
/blog/categories/big%20data
/blog/categories/build%20times
/blog/categories/cloud%20block%20storage
/blog/categories/cloud%20databases
/blog/categories/cloud%20files
/blog/categories/cloud%20images
/blog/categories/cloud%20load%20balancers
/blog/categories/cloud%20monitoring
/blog/categories/cloud%20networks
/blog/categories/cloud%20servers
/blog/categories/cloud%20tools
/blog/categories/configuration%20management
/blog/categories/custom%20images
/blog/categories/data%20science
/blog/categories/food%20policy%20council
/blog/categories/guest%20posts
/blog/categories/jenkins%20ci
/blog/categories/managed%20cloud
/blog/categories/node.js
/blog/categories/open%20source
/blog/categories/performance%20cloud%20servers
/blog/categories/private%20cloud
/blog/categories/public%20cloud
/blog/categories/support%20non-profit
/blog/categories/user%20management
/blog/categories/v9.0
/blog/categories/zend%20framework%202
```

These don't render on current dev rax either, but they were found while I was spidering. That's not the full list either, my new run is still going.

**Comment by smashwilson** [comment]
> Reported several of the issues.

:+1: Sweet, thanks!

For future reference, we're consolidating issues here on deconst-docs for deconst infrastructure stuff, just to keep it all together in a single milestone and not lose track of anything. (Hmm, I should disable issues on the other repositories...)

> These don't render on current dev rax either...

Ah - that's less of a priority for our launch, then. It might be an issue with the Jekyll plugin we're using to generate the page categories?

**Comment by smashwilson** [comment]
Okay, the deconst-hosted version has been up and stable for a while now. I think it's time to :hocho: the old infra. (It's also pretty out of date at this point, so its utility as a warm backup has diminished substantially.)

**Comment by smashwilson** [comment]
:confetti_ball:

**Comment by rgbkrk** [comment]
:tada:
