### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#72]
Today, we're assembling every page on the fly, from scratch, at request time. That's simple and ensures that everything is always up to date, but it's slower than it has to be.

We can easily introduce a caching layer to save effort and get a quick boost in render time. We can either:
- Introduce something like memcached into the architecture, or:
- We can just implement an in-memory cache directly in the presenter.

I'd prefer if we had some way to manually bust the cache to expedite time-sensitive updates.

**Comment by rgbkrk** [comment]
If you include memcache, you definitely have a way to bust the cache. I do this all the time.

**Comment by smashwilson** [comment]
Closing in favor of #141.
