### ISSUE TITLE
Normalize URLs

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#83]
> If `/blog/stuff/` exists, then `/blog/////stuff///` should point to the content as well, according to RFC 3986, > section 3.3 on path:
> 
> ```
> path-abempty  = *( "/" segment )
> ```
> 
> Try it out on this issue page to see for yourself. Originally noted in
> https://github.com/////////deconst/deconst-docs/issues//////////////////////////////////71

Moved here from deconst/mapping-service#31.

**Comment by smashwilson** [comment]
We should actually use redirects for this, rather than accepting both forms of the URL.

That should also be true for trailing-slash normalization.

**Comment by smashwilson** [comment]
@ktbartholomew: It looks like this regressed with the presenter rewrite:

https://developer.rackspace.com/docs/user-guides/infrastructure

Also, I'm not sure that we were handling extraneous slashes like the original issue reported, just trailing ones.

**Comment by ktbartholomew** [comment]
I'll get it back!

**Comment by ktbartholomew** [comment]
Fixed again (including empty segments) by [deconst/presenter#48](https://github.com/deconst/presenter/pull/48) and [rackerlabs/nexus-control#43](https://github.com/rackerlabs/nexus-control/pull/43)

**Comment by annegentle** [comment]
Might have regressed again with the email report on our support list.
