### ISSUE TITLE
Include "next" and "previous" elements from Sphinx

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#89]
The Jekyll preparer [already emits `next` and `previous` elements](https://github.com/deconst/preparer-jekyll/blob/master/lib/preparermd/plugins/metadata_envelopes.rb#L64-L67) in its metadata envelopes. The Sphinx preparer should do the same, so that layouts for Sphinx content can include navigation controls.

Here's the schema they should follow, for consistency:

``` json
{
  "next": { "url": "/relative/to/doc/root", "title": "Page Title" },
  "previous": { "url": "/relative/to/repo/root", "title": "Page Title" }
}
```
- [x] _<sphinx preparer>_ Include conforming `next` and `previous` elements in generated metadata envelopes.
- [x] _<mapping-service>_ Return both the mapped prefix and the content ID from the mapping service call.
- [x] _<presenter>_ Use the prefix to manipulate any absolute `next` and `previous` urls present in the metadata envelope prior to rendering.

/cc @annegentle

**Comment by smashwilson** [comment]
There's another complication here. When the envelope is being generated, the content repository has no way of knowing where it's "mounted" within the final page - you can even move it after the fact by messing with the control repo! This makes the problem of generating nav links correctly a bit of a problem.

For example, if a page at `/foo/one` has a "next page" of `/foo/two`, but the entire content repository is mounted at `/docs`, the final "next" link should _actually_ point to `/docs/foo/two`.

The only reason it works for the Jekyll content is because [we happen to mount that at `/`](https://github.com/rackerlabs/nexus-control/blob/master/drc.map.txt#L2), so we were able to sidestep the issue to get 0.2 out the door. Getting this to work for Sphinx will be more involved because we need to adjust the `url` elements the envelope to be rooted at the correct place.

**Comment by kenperkins** [comment]
Isn't this just combining the mount point with the url?

**Comment by smashwilson** [comment]
That's the basic idea, yes. We need to change the mapping service to return both the mount point and the final content ID, then change the presenter to propagate that through and manipulate the outgoing metadata envelope to prefix it on the url elements.

**Comment by smashwilson** [comment]
This is also somewhat related to #38. Most content engines have some capacity for generating URLs to link around their content. All of them will break deconst if the content repository is mapped anywhere but `/`. I'm not sure what we can do when someone [sidesteps the markup entirely and hardcodes URLs as raw HTML](https://raw.githubusercontent.com/rackerlabs/docs-quickstart/master/index.rst), either.

That's a discussion for another issue, though. I think we can get the next and previous URLs up without too much trouble.

**Comment by smashwilson** [comment]
There. We can now use:
- `{{ envelope.next.url }}`
- `{{ envelope.next.title }}`
- `{{ envelope.previous.url }}`
- `{{ envelope.previous.title }}`

... in any Handlebars layouts in a control repository. :sparkles:
